### ISSUE TITLE
Breaks loading tracks

### ISSUE THREAD

**Issue by AndyIsHereBoi** [Calculamatrise/frhd-lite#2]
When the extension is enabled then i try to load a track i just get this and it never seems to finish. 
![image](https://user-images.githubusercontent.com/69745145/198284495-3eaf5f6b-1128-472f-a16f-d0719debb783.png)

**Comment by AndyIsHereBoi** [comment]
It also appears to not disable when i try to click the disable button on the extension

**Comment by Calculamatrise** [comment]
Hi @AndyIsHereBoi,

This has been a long lasting issue and it is most likely due to the use of ECMAScript. Being that Free Rider Lite's codebase is made easy to work with, I haven't been minifying the extension. The next version will be minified and include lots of bug fixes and quality of life improvements.

Stay tuned!

**Comment by AndyIsHereBoi** [comment]
Ok
